# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-ChangesRSS
version:      0.01
version_from: lib/WebService/ChangesRSS.pm
installdirs:  site
requires:
    HTTP::Date:                    0
    LWP::UserAgent:                0
    Test::More:                    0.32
    XML::RSS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
